package hw3.enums;

public enum Header {
    MAIN("EPAM FRAMEWORK WISHES…"),
    JDI("LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISICING ELIT, " +
            "SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. " +
            "UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT "+
            "ALIQUIP EX EA COMMODO CONSEQUAT DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT "+
            "ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR.");

    public final String text;

    Header(String text) {
        this.text = text;
    }
}
